version: '3.1'

services:

  dashboard:
    container_name: vfr-dashboard
    image: videofacerecognition/dashboard
    build: packages/dashboard
    restart: always
    networks:
      - video-face-recognition
    ports:
      - 9000:8080
    depends_on:
      - persistence

  persistence:
    container_name: vfr-persistence
    image: videofacerecognition/persistence
    build: packages/persistence
    restart: always
    networks:
      - video-face-recognition
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vfr
    ports:
      - 9001:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - video-face-recognition
    ports:
      - 9002:8080

networks:
  video-face-recognition:
volumes:
  pg_data:
