version: '3.1'

services:

  nginx:
    container_name: vfr-nginx
    depends_on:
      - api
      - dashboard
    image: nginx
    volumes:
      - ./.data/nginx/logs:/var/log/nginx
      - ./conf/nginx:/etc/nginx
    networks:
      - video-face-recognition
    ports:
      - 10000:80

  dashboard:
    container_name: vfr-dashboard
    image: videofacerecognition/dashboard
    build: packages/dashboard
    restart: always
    networks:
      - video-face-recognition
    ports:
      - 9000:8080
    depends_on:
      - persistence

  persistence:
    container_name: vfr-persistence
    image: videofacerecognition/persistence
    build: packages/persistence
    restart: always
    networks:
      - video-face-recognition
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vfr
    ports:
      - 9001:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - video-face-recognition
    ports:
      - 9002:8080

  api:
    command: ["node", "packages/api/dist/index.js"]
    working_dir: /app
    container_name: vfr-api
    image: node:10
    restart: always
    networks:
      - video-face-recognition
    ports:
      - 9003:80
    volumes:
      - ./:/app
    depends_on:
      - persistence

networks:
  video-face-recognition:
volumes:
  pg_data:
